main:
	gcc -Wall savitr.c savitr_main.c -o savitr

timer:
	gcc -Wall savitr.c savitr_timer.c -o savitr_timer

test:
	gcc -Wall savitr.c savitr_test.c -o savitr_test

cleanWIN:
	del savitr.exe savitr_test.exe savitr_timer.exe

clean:
	rm savitr savitr_test savitr_timer